@extends('MatriculaPostulante.personas.fieldsPersonaPadres', 
    [
'PNombreLBL' => 'madre[PNombre]',
'SNombreLBL' => 'madre[SNombre]',
'TNombreLBL' => 'madre[TNombre]',
'ApPatLBL' => 'madre[ApPat]',
'ApMatLBL' => 'madre[ApMat]',
'fonoFijoLBL' => 'madre[fonoFijo]',
'fonoCeluLBL' => 'madre[fonoCelu]',
'rutLBL' => 'madre[rut]',
'generoLBL' => 'madre[genero]',
'emailLBL' => 'madre[email]',
'estadoCivilLBL' => 'madre[estadoCivil]',
'idAlumnoLBL' => 'madre[idAlumno]',
'parentescoLBL' => 'madre[parentesco]',
'fechaDefuncionLBL' => 'madre[fechaDefuncion]',
'fechaNacimientoLBL' => 'madre[fechaNacimiento]',
'nivelEducacionalLBL' => 'madre[nivelEducacional]',
'profesionLBL' => 'madre[profesion]',
'paisDeOrigenLBL' => 'madre[paisDeOrigen]',


'idComunaLBL' => "madre[direccion][idComuna]",
'calleLBL' => 'madre[direccion][calle]',
'nroCalleLBL' => 'madre[direccion][nroCalle]',
'dptoLBL' => 'madre[direccion][dpto]',
'bloqueTorreLBL' => 'madre[direccion][bloqueTorre]',


'PNombreTXT' =>( isset($madre->PNombre) ? $madre->PNombre : null ), 
'SNombreTXT' => ( isset($madre->SNombre) ? $madre->SNombre : null ),
'TNombreTXT' =>( isset($madre->TNombre) ? $madre->TNombre : null ),
'ApPatTXT' => ( isset($madre->ApPat) ? $madre->ApPat : null ),
'ApMatTXT' => ( isset($madre->ApMat) ? $madre->ApMat : null ),
'fonoFijoTXT' => ( isset($madre->fonoFijo) ? $madre->fonoFijo : null ),
'fonoCeluTXT' =>( isset($madre->fonoCelu) ? $madre->fonoCelu : null ),
'rutTXT' => ( isset($madre->rut) ? $madre->rut : null ),
'generoTXT' => ( isset($madre->genero) ? $madre->genero : null ),
'emailTXT' => ( isset($madre->email) ? $madre->email : null ),
'estadoCivilTXT' => ( isset($madre->estadoCivil) ? $madre->estadoCivil : null ),
'idAlumnoTXT' => ( isset($persona->alumno->id) ? $persona->alumno->id : null ),
'parentescoTXT' => ( isset($madre->parentesco) ? $madre->parentesco : null ),
'fechaDefuncionTXT' => ( isset($madre->fechaDefuncion) ? $madre->fechaDefuncion : null ),

'fechaNacimientoTXT' => ( isset($madre->fechaNacimiento) ? $madre->fechaNacimiento : null ),
'nivelEducacionalTXT' => ( isset($madre->nivelEducacional) ? $madre->nivelEducacional : null ),
'profesionTXT' => ( isset($madre->profesion) ? $madre->profesion : null ),
'paisDeOrigenTXT' => ( isset($madre->paisDeOrigen) ? $madre->paisDeOrigen : null ),



'idComunaTXT' => ( isset($madre->direccion->idComuna) ? $madre->direccion->idComuna : null ),
'calleTXT' => ( isset($madre->direccion->calle) ? $madre->direccion->calle : null ),
'nroCalleTXT' => ( isset($madre->direccion->nroCalle) ? $madre->direccion->nroCalle : null ),
'dptoTXT' => ( isset($madre->direccion->dpto) ? $madre->direccion->dpto : null ),
'bloqueTorreTXT' => ( isset($madre->direccion->bloqueTorre) ? $madre->direccion->bloqueTorre : null ),
    ])